name       : parallel
version    : '20170522'
release    : 5
source     :
    - https://ftp.gnu.org/gnu/parallel/parallel-20170522.tar.bz2 : 8a0d51632921b80102817151b62ea17eed6b28d088c40d94ed4ee40618a3bccc
license    : GPL-3.0
component  : programming.tools
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
