name       : parallel
version    : '20170122'
release    : 4
source     :
    - http://ftp.gnu.org/gnu/parallel/parallel-20170122.tar.bz2 : 417e83d9de2fe518a976fcff5a96bffe41421c2a57713cd5272cc89d1072aaa6
license    : GPL-3.0
component  : programming.tools
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
