name       : parallel
version    : '20181222'
release    : 7
source     :
    - https://mirrors.rit.edu/gnu/parallel/parallel-20181222.tar.bz2 : 058c9f7cf599652aef5b54cf5c95c9a5b6d57d59ce4deebebf7938f7be4da369
license    : GPL-3.0
component  : programming.tools
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
