name       : parallel
version    : '20210722'
release    : 8
source     :
    - https://mirrors.rit.edu/gnu/parallel/parallel-20210722.tar.bz2 : 3239094bc043957be191e1e4376716ef0d1b369e545b5bf7d7824b7d46284a49
license    : GPL-3.0-or-later
component  : programming.tools
homepage   : https://www.gnu.org/software/parallel/
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # remove html, rst, and pdf docs
    rm -rf $installdir/usr/share/doc
