name       : parallel
version    : 20161122
release    : 3
source     :
    - http://ftp.gnu.org/gnu/parallel/parallel-20161122.tar.bz2 : e2595011494b557822134bd6ad73c8d455764cdf51d148005346a4564626ac7c
license    : GPL-3.0
component  : programming.tools
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
