name        : parallel
version     : 20150222
release     : 2
source      :
    - ftp://ftp.gnu.org/gnu/parallel/parallel-20150222.tar.bz2 : 675fddfeb81d0a3730246d21f9fa89934b29770e910982d049882905a0d5028c
license     :
    - GPLv3+
summary     : Execute jobs in parallel
description : |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
