name       : parallel
version    : '20211022'
release    : 10
source     :
    - https://mirrors.rit.edu/gnu/parallel/parallel-20211022.tar.bz2 : da7190fce22a9cda97b2ce36df112a2c634f1b4a5591af343b928253e996de9b
license    : GPL-3.0-or-later
component  : programming.tools
homepage   : https://www.gnu.org/software/parallel/
summary    : Execute jobs in parallel
description: |
    GNU parallel is a shell tool that allows for execution of jobs in parallel. This source file also contains a command line SQL client (sql) and a tool for nicing jobs (niceload).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # remove html, rst, and pdf docs
    rm -rf $installdir/usr/share/doc
